# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_id', models.IntegerField(blank=True, null=True, verbose_name=b'')),
                ('official_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'official_identifier')),
                ('official_identifier_slug', models.SlugField(blank=True, max_length=140, null=True, verbose_name=b'official_identifier_slug')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_short_summary', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_summary', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_summary_author', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_yes_vote_means', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_no_vote_means', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_vote_means_source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_financial_effect', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_financial_effect_author', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_impartial_analysis', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_impartial_analysis_author', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_background', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_background_author', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_tax_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_tax_rate_author', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_short_arguments_yes', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_short_arguments_no', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_short_arguments_source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_arguments_yes', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_arguments_no', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_arguments_source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('official_rebuttal_yes', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('official_rebuttal_no', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('measure_type', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('passage_requirements', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('fulltext_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name=b'fulltext_link')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('simplified_title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('way_it_is', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('what_if_pass', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('budget_effect', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('people_for_say', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('people_against_say', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('evg_source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('lwv_question', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_situation', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_proposal', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_fiscal_effects', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_supporters_say', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_opponents_say', models.TextField(blank=True, null=True, verbose_name=b' ')),
                ('lwv_source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('votes_for', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('votes_against', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('published', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('disable_finance_data', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('deleted', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('measure_timestamp', models.DateTimeField(blank=True, null=True, verbose_name=b'')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_top_id', models.IntegerField(blank=True, null=True, verbose_name=b'')),
                ('top_type', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('support', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_individual', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_organization', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_total', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_individual', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_organization', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name=b'')),
                ('entity_type', models.IntegerField(blank=True, null=True, verbose_name=b'')),
                ('finance_top_timestamp', models.DateTimeField(blank=True, null=True, verbose_name=b'')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Date Modified')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maplight_finance.Measure')),
            ],
        ),
    ]
