# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maplight_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_id', models.IntegerField(blank=True, null=True, verbose_name=b'')),
                ('support', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_individual', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_unitemized', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_itemized', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('total_organization', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_individual', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_organization', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_unitemized', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('percentage_itemized', models.FloatField(blank=True, null=True, verbose_name=b'')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name=b'')),
                ('entity_type', models.IntegerField(blank=True, null=True, verbose_name=b'')),
                ('finance_timestamp', models.DateTimeField(blank=True, null=True, verbose_name=b'')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Date Modified')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maplight_finance.Measure')),
            ],
        ),
    ]
