# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplight_finance', '0002_measuretotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='budget_effect',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='evg_source',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_fiscal_effects',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_opponents_say',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_proposal',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_question',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_situation',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_source',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='lwv_supporters_say',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='official_arguments_no',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='official_arguments_source',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='official_arguments_yes',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='official_background',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='official_background_author',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='people_against_say',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='people_for_say',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='simplified_title',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='votes_against',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='votes_for',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='way_it_is',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='what_if_pass',
        ),
    ]
