# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kpcc_backroom_handshakes.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0003_resultsource_ready_to_build'),
        ('newscast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contest ID')),
                ('cities_counties_list', kpcc_backroom_handshakes.custom_fields.ListField(blank=True, null=True, verbose_name='Cities and Counties')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About This Contest')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_registrar.Election')),
            ],
        ),
    ]
