# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0003_resultsource_ready_to_build'),
        ('newscast', '0003_contestcontext_local_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareTurnout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='State or the County')),
                ('election_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Election Type')),
                ('formal_date', models.DateField(auto_now_add=True, verbose_name='Election Date')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Election Year')),
                ('registered_voters', models.IntegerField(blank=True, null=True, verbose_name='Registered Voters')),
                ('ballots_cast', models.IntegerField(blank=True, null=True, verbose_name='Ballots Cast')),
                ('turnout', models.FloatField(blank=True, null=True, verbose_name='Turnout')),
                ('vote_by_mail_ballots', models.IntegerField(blank=True, null=True, verbose_name='Vote By Mail Ballots')),
                ('vote_by_mail_percent', models.FloatField(blank=True, null=True, verbose_name='Vote By Mail Percent')),
                ('data_source', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL To Turnout Data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_registrar.Election')),
            ],
        ),
    ]
