# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0001_initial'),
        ('newscast', '0004_compareturnout'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='measure',
            field=models.ManyToManyField(to='ballot_box.BallotMeasure'),
        ),
    ]
