# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscast', '0005_topic_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='measure',
        ),
    ]
