# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kpcc_backroom_handshakes.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0003_resultsource_ready_to_build'),
        ('newscast', '0006_remove_topic_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='State or the County the nugget came from')),
                ('nugget_text', models.TextField(blank=True, null=True, verbose_name='Latest Update')),
                ('nugget_date', models.DateField(auto_now_add=True, verbose_name='Date of this Information')),
                ('nugget_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the Sources')),
                ('nugget_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL To Source')),
                ('nugget_tags', kpcc_backroom_handshakes.custom_fields.ListField(blank=True, null=True, verbose_name='Cities and Counties')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_registrar.Election')),
            ],
        ),
    ]
