# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import kpcc_backroom_handshakes.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('newscast', '0007_datanugget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanugget',
            name='nugget_date',
            field=models.DateField(verbose_name='Date of this Information'),
        ),
        migrations.AlterField(
            model_name='datanugget',
            name='nugget_tags',
            field=kpcc_backroom_handshakes.custom_fields.ListField(blank=True, null=True, verbose_name='Topic Tags'),
        ),
    ]
