version: '3.3'

services:

  backroom-handshakes: 
    build: .
    container_name: backroom-handshakes-python
    ports:
      - 8000:8000/tcp
    networks:
      backroom-handshakes-network:
        aliases:
          - python
    volumes:
      - ./:/home/
    command: /bin/sh
    stdin_open: true
    tty: false
    depends_on:
      - mysql

  mysql:
    image: mariadb
    container_name: backroom-handshakes-mysql
    ports:
      - 3200:3200/tcp
      - 3306:3306/tcp
    restart: always
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
    # volumes:
    #   - mysql-data:/var/lib/mysql
    networks:
      backroom-handshakes-network:
        aliases:
         - mysql

  node:
    image: node:9.11.1-alpine
    container_name: node
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/


volumes:
  mysql-data:

networks:
  backroom-handshakes-network: