# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure_finance', '0002_auto_20160916_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measuretotal',
            old_name='percentage_individual',
            new_name='pct_individual',
        ),
        migrations.RenameField(
            model_name='measuretotal',
            old_name='percentage_itemized',
            new_name='pct_itemized',
        ),
        migrations.RenameField(
            model_name='measuretotal',
            old_name='percentage_organization',
            new_name='pct_organization',
        ),
        migrations.RenameField(
            model_name='measuretotal',
            old_name='percentage_unitemized',
            new_name='pct_unitemized',
        ),
    ]
