# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0003_resultsource_ready_to_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_title',
            field=models.TextField(blank=True, null=True, verbose_name=b'Audience-facing display of election title'),
        ),
    ]
