# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0004_election_election_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_title',
            field=models.CharField(default='None', max_length=255, verbose_name=b'Audience-facing display of election title'),
            preserve_default=False,
        ),
    ]
