# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_registrar', '0006_election_election_kpcc_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsource',
            name='source_all_precincts',
            field=models.BooleanField(default=False, verbose_name=b'100% precincts reporting'),
        ),
    ]
