# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election_registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureid', models.CharField(max_length=255, verbose_name='Measure ID')),
                ('ballotorder', models.IntegerField(blank=True, null=True, verbose_name='Numerical Position On The Ballot')),
                ('fullname', models.CharField(max_length=255, verbose_name='Name of Ballot Measure')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description Of Ballot Measure')),
                ('yescount', models.IntegerField(blank=True, null=True, verbose_name='Number Of Yes Votes Received')),
                ('yespct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Yes Votes Received')),
                ('nocount', models.IntegerField(blank=True, null=True, verbose_name='Number Of No Votes Received')),
                ('nopct', models.FloatField(blank=True, null=True, verbose_name='Percent Of No Votes Received')),
                ('poss_error', models.BooleanField(default=False, verbose_name='Possible Error')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate ID')),
                ('ballotorder', models.IntegerField(blank=True, null=True, verbose_name='Numerical Position On The Ballot')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's First Name")),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Last Name")),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Full Name")),
                ('party', models.CharField(blank=True, max_length=255, null=True, verbose_name='Political Party')),
                ('incumbent', models.BooleanField(default=False, verbose_name='Is Candidate An Incumbent?')),
                ('votecount', models.IntegerField(blank=True, null=True, verbose_name='Votes Received')),
                ('votepct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Total Votes')),
                ('poss_error', models.BooleanField(default=False, verbose_name='Possible Error')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contest ID')),
                ('contestname', models.CharField(max_length=255, verbose_name='Contest')),
                ('seatnum', models.IntegerField(blank=True, null=True, verbose_name='Number of district or seat up for grabs')),
                ('contestdescription', models.TextField(blank=True, null=True, verbose_name='Description Of This Contest')),
                ('is_uncontested', models.BooleanField(default=False, verbose_name='Uncontested Contest?')),
                ('is_national', models.BooleanField(default=False, verbose_name='National Contest?')),
                ('is_statewide', models.BooleanField(default=False, verbose_name='Statewide Contest?')),
                ('is_ballot_measure', models.BooleanField(default=False, verbose_name='Is A Measure?')),
                ('is_judicial', models.BooleanField(default=False, verbose_name='Is Judicial Contest?')),
                ('is_runoff', models.BooleanField(default=False, verbose_name='Is A Runoff Contest?')),
                ('is_display_priority', models.BooleanField(default=False, verbose_name='Interested In?')),
                ('is_homepage_priority', models.BooleanField(default=False, verbose_name='Feature This?')),
                ('reporttype', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status of Results')),
                ('precinctstotal', models.IntegerField(blank=True, null=True, verbose_name='Total Number Of Precincts')),
                ('precinctsreporting', models.IntegerField(blank=True, null=True, verbose_name='Precincts Reporting')),
                ('precinctsreportingpct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Precincts Reporting')),
                ('votersregistered', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Registered Voters')),
                ('votersturnout', models.FloatField(blank=True, null=True, verbose_name='Percent Voters Who Cast Ballots')),
                ('poss_error', models.BooleanField(default=False, verbose_name='Possible Error')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_registrar.Election')),
            ],
        ),
        migrations.CreateModel(
            name='JudicialCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgeid', models.CharField(max_length=255, verbose_name='Judicial Candidate ID')),
                ('ballotorder', models.IntegerField(blank=True, null=True, verbose_name='Numerical Position On The Ballot')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's First Name")),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Last Name")),
                ('fullname', models.CharField(max_length=255, verbose_name="Candidate's Last Name")),
                ('yescount', models.IntegerField(blank=True, null=True, verbose_name='Number Of Yes Votes Received')),
                ('yespct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Yes Votes Received')),
                ('nocount', models.IntegerField(blank=True, null=True, verbose_name='Number Of No Votes Received')),
                ('nopct', models.FloatField(blank=True, null=True, verbose_name='Percent Of No Votes Received')),
                ('poss_error', models.BooleanField(default=False, verbose_name='Possible Error')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name Of The Office')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug Of The Office')),
                ('officeid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Office ID')),
                ('active', models.BooleanField(default=False, verbose_name='Is This Office Active?')),
                ('poss_error', models.BooleanField(default=False, verbose_name='Possible Error')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Office'),
        ),
        migrations.AddField(
            model_name='contest',
            name='resultsource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_registrar.ResultSource'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Contest'),
        ),
        migrations.AddField(
            model_name='ballotmeasure',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Contest'),
        ),
    ]
