# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name of data source')),
                ('source_short', models.CharField(max_length=5, verbose_name='Shortname of data source')),
                ('source_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slugged data soure')),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL to data source')),
                ('source_active', models.BooleanField(default=False, verbose_name='Active data source?')),
                ('source_type', models.CharField(max_length=255, verbose_name='Ext of file or type of source')),
                ('source_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('source_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
