# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_image',
            field=models.BooleanField(default=False, verbose_name='Do We Have a Candidate Image?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL To Image'),
        ),
    ]
