# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsource',
            name='source_election_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of election for this source'),
        ),
    ]
