# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 18:19
from __future__ import unicode_literals

from django.db import migrations
import kpcc_backroom_handshakes.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0002_resultsource_source_election_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsource',
            name='source_files',
            field=kpcc_backroom_handshakes.custom_fields.ListField(blank=True, null=True, verbose_name='Results Files We Want'),
        ),
    ]
