# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0003_resultsource_source_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('General', 'General'), ('Special', 'Special')], default='Primary', max_length=255, verbose_name='Type of Election')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Election ID')),
                ('test_results', models.BooleanField(default=False, verbose_name='Are These Test Results')),
                ('live_results', models.BooleanField(default=False, verbose_name='Are These Live Results')),
                ('election_date', models.DateField(blank=True, null=True, verbose_name='Date of the Election')),
                ('poll_close_at', models.DateTimeField(blank=True, null=True, verbose_name='Time the Polls Close')),
                ('national', models.BooleanField(default=False, verbose_name='Is this a National Election?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultsource',
            name='source_election_date',
        ),
        migrations.AddField(
            model_name='resultsource',
            name='election',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Election'),
            preserve_default=False,
        ),
    ]
