# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0004_auto_20160505_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='unique_id',
            new_name='electionid',
        ),
    ]
