# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0004_auto_20160505_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('General', 'General'), ('Special', 'Special')], default='Primary', max_length=255, verbose_name='Type of Election')),
                ('test_results', models.BooleanField(default=False, verbose_name='Are These Test Results')),
                ('live_results', models.BooleanField(default=False, verbose_name='Are These Live Results')),
                ('election_date', models.DateField(blank=True, null=True, verbose_name='Date of the Election')),
                ('poll_close_at', models.DateTimeField(blank=True, null=True, verbose_name='Time the Polls Close')),
                ('national', models.BooleanField(default=False, verbose_name='Is this a National Election?')),
                ('unique_id', models.CharField(max_length=255, verbose_name='Ext of file or type of source')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
