# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0005_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Election ID'),
        ),
    ]
