# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0006_auto_20160510_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name Of The Office')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slugged Data Soure')),
                ('active', models.BooleanField(default=False, verbose_name='Is This Office Active?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
        ),
    ]
