# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0007_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.CharField(max_length=255, verbose_name='Contest ID')),
                ('contestname', models.CharField(max_length=255, verbose_name='Proper Reference To This Contest')),
                ('seatnum', models.IntegerField(blank=True, null=True, verbose_name='Number of district or seat up for grabs')),
                ('contestdescription', models.TextField(blank=True, null=True, verbose_name='Description Of This Contest')),
                ('is_uncontested', models.BooleanField(default=False, verbose_name='Uncontested Contest?')),
                ('is_national', models.BooleanField(default=False, verbose_name='National Contest?')),
                ('is_statewide', models.BooleanField(default=False, verbose_name='Statewide Contest?')),
                ('is_ballot_measure', models.BooleanField(default=False, verbose_name='Is A Measure?')),
                ('is_judicial', models.BooleanField(default=False, verbose_name='Is Judicial Contest?')),
                ('is_runoff', models.BooleanField(default=False, verbose_name='Is A Runoff Contest?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('contesttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Office')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Election')),
                ('resultsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.ResultSource')),
            ],
        ),
    ]
