# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0008_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.CharField(max_length=255, verbose_name='Candidate ID')),
                ('ballotorder', models.IntegerField(blank=True, null=True, verbose_name='Numerical Position On The Ballot')),
                ('firstname', models.CharField(max_length=255, verbose_name="Candidate's First Name")),
                ('lastname', models.CharField(max_length=255, verbose_name="Candidate's Last Name")),
                ('fullname', models.CharField(max_length=255, verbose_name="Candidate's Last Name")),
                ('party', models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Political Party")),
                ('incumbent', models.BooleanField(default=False, verbose_name='Is Candidate An Incumbent?')),
                ('votecount', models.IntegerField(blank=True, null=True, verbose_name='Number Of Votes Received')),
                ('votepct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Votes Received')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Contest')),
            ],
        ),
    ]
