# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0011_judicialcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportingunitname', models.CharField(max_length=255, verbose_name='Name Of The Reporing Entity')),
                ('reportingunitslug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug Of The Reporing Entity')),
                ('precinctstotal', models.IntegerField(blank=True, null=True, verbose_name='Total Number Of Precincts')),
                ('precinctsreporting', models.IntegerField(blank=True, null=True, verbose_name='Number Of Precincts That Have Reported Votes')),
                ('precinctsreportingpct', models.FloatField(blank=True, null=True, verbose_name='Percent Of Precincts Reporting')),
                ('votersregistered', models.FloatField(blank=True, null=True, verbose_name='Number of Registered Voters')),
                ('votersturnout', models.FloatField(blank=True, null=True, verbose_name='Percent Of Registered Voters Who Cast Ballots')),
                ('statename', models.CharField(max_length=255, verbose_name="Name Of The Reporing Entity's State")),
                ('statepostal', models.CharField(max_length=2, verbose_name="Postal Code Of The Reporing Entity's State")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description Of Ballot Measure')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Contest')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_box.Election')),
            ],
        ),
    ]
