# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0012_reportingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contest ID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug Of The Office'),
        ),
    ]
