# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0014_auto_20160511_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's First Name"),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Last Name"),
        ),
        migrations.AlterField(
            model_name='judicialcandidate',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's First Name"),
        ),
        migrations.AlterField(
            model_name='judicialcandidate',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Candidate's Last Name"),
        ),
    ]
