# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0015_auto_20160511_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingunit',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='reportingunit',
            name='election',
        ),
        migrations.AddField(
            model_name='contest',
            name='precinctsreporting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of Precincts That Have Reported Votes'),
        ),
        migrations.AddField(
            model_name='contest',
            name='precinctsreportingpct',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Of Precincts Reporting'),
        ),
        migrations.AddField(
            model_name='contest',
            name='precinctstotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number Of Precincts'),
        ),
        migrations.AddField(
            model_name='contest',
            name='votersregistered',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of Registered Voters'),
        ),
        migrations.AddField(
            model_name='contest',
            name='votersturnout',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Of Registered Voters Who Cast Ballots'),
        ),
        migrations.DeleteModel(
            name='ReportingUnit',
        ),
    ]
