# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 20:45
from __future__ import unicode_literals

from django.db import migrations
import kpcc_backroom_handshakes.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0018_contest_reporttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsource',
            name='source_url',
        ),
        migrations.AddField(
            model_name='resultsource',
            name='source_urls',
            field=kpcc_backroom_handshakes.custom_fields.ListField(blank=True, null=True, verbose_name='Urls To Data Source'),
        ),
    ]
