# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0019_auto_20160514_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsource',
            name='source_latest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
    ]
