# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0020_resultsource_source_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsource',
            name='source_urls',
        ),
        migrations.AddField(
            model_name='resultsource',
            name='source_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Url To Data Source'),
        ),
        migrations.AlterField(
            model_name='resultsource',
            name='source_latest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest Results From'),
        ),
    ]
