# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0021_auto_20160514_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_display_priority',
            field=models.BooleanField(default=False, verbose_name='Display this race?'),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_homepage_priority',
            field=models.BooleanField(default=False, verbose_name='Display race on homepage?'),
        ),
    ]
