# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0022_auto_20160516_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotmeasure',
            name='poss_error',
            field=models.BooleanField(default=False, verbose_name='Possible Error'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='poss_error',
            field=models.BooleanField(default=False, verbose_name='Possible Error'),
        ),
        migrations.AddField(
            model_name='contest',
            name='poss_error',
            field=models.BooleanField(default=False, verbose_name='Possible Error'),
        ),
        migrations.AddField(
            model_name='judicialcandidate',
            name='poss_error',
            field=models.BooleanField(default=False, verbose_name='Possible Error'),
        ),
        migrations.AddField(
            model_name='office',
            name='poss_error',
            field=models.BooleanField(default=False, verbose_name='Possible Error'),
        ),
        migrations.AlterField(
            model_name='ballotmeasure',
            name='nocount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of No Votes Received'),
        ),
        migrations.AlterField(
            model_name='ballotmeasure',
            name='nopct',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Of No Votes Received'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_display_priority',
            field=models.BooleanField(default=False, verbose_name='Interested In This Race?'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_homepage_priority',
            field=models.BooleanField(default=False, verbose_name='Feature This Race?'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='votersregistered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Registered Voters'),
        ),
    ]
