# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0023_auto_20160519_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='officeid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office ID'),
        ),
        migrations.AlterField(
            model_name='judicialcandidate',
            name='nocount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of No Votes Received'),
        ),
        migrations.AlterField(
            model_name='judicialcandidate',
            name='nopct',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Of No Votes Received'),
        ),
    ]
