# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_box', '0025_auto_20160524_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestname',
            field=models.CharField(max_length=255, verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_display_priority',
            field=models.BooleanField(default=False, verbose_name='Interested In?'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_homepage_priority',
            field=models.BooleanField(default=False, verbose_name='Feature This?'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='precinctsreporting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precincts Reporting'),
        ),
        migrations.AlterField(
            model_name='election',
            name='national',
            field=models.BooleanField(default=False, verbose_name='Is National Election?'),
        ),
        migrations.AlterField(
            model_name='election',
            name='poll_close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Polls Close'),
        ),
        migrations.AlterField(
            model_name='resultsource',
            name='source_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Data Source Name'),
        ),
        migrations.AlterField(
            model_name='resultsource',
            name='source_short',
            field=models.CharField(max_length=5, verbose_name='Data Source Shortname'),
        ),
        migrations.AlterField(
            model_name='resultsource',
            name='source_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slugged Data Source'),
        ),
    ]
